# Generated by Django 4.1.3 on 2023-03-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workersreg_category_workersreg_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoty', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
