# Generated by Django 4.1.3 on 2023-03-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
