# Generated by Django 4.1.3 on 2023-03-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_categoty_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoty',
            new_name='category',
        ),
    ]
