# Generated by Django 4.1.3 on 2023-03-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='notbooked', max_length=100, null=True),
        ),
    ]
