# Generated by Django 4.1.3 on 2023-03-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='worid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
