# Generated by Django 4.1.3 on 2023-03-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_useraddfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('usrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userreg')),
            ],
        ),
    ]
