# Generated by Django 4.1.3 on 2023-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersreg',
            name='wages',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
