# Generated by Django 4.1.3 on 2023-03-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_wages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
    ]
