# Generated by Django 4.1.3 on 2023-03-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workeraddfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('worrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userreg')),
            ],
        ),
    ]
