# Generated by Django 4.1.3 on 2023-03-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_workeraddfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workeraddfeedback',
            name='worrid',
        ),
        migrations.AddField(
            model_name='workeraddfeedback',
            name='worid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workersreg'),
        ),
    ]
