# Generated by Django 4.1.3 on 2023-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_workeraddfeedback_worrid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
