# Generated by Django 5.2.9 on 2026-03-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddfeedback',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
        ),
    ]
