# Generated by Django 5.2.9 on 2026-03-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_useraddfeedback_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeraddfeedback',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
        ),
        migrations.AddField(
            model_name='workeraddfeedback',
            name='usrid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userreg'),
        ),
    ]
